// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseWords(arg1:any,arg2:any,arg3:any,arg4:any):Promise<main.BrowseResult>;

export function DownloadDB(arg1:any):Promise<string>;

export function GetAPIKey():Promise<any>;

export function GetEntry(arg1:number):Promise<main.FullEntryDetail>;

export function GetLanguages():Promise<Array<main.LanguageMeta>>;

export function SearchFTS(arg1:string,arg2:any,arg3:any,arg4:any):Promise<Array<main.SearchResult>>;

export function SearchVector(arg1:Array<number>,arg2:any):Promise<Array<main.SearchResult>>;

export function SetAPIKey(arg1:string):Promise<void>;
