// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseWords(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseWords'](arg1, arg2, arg3, arg4);
}

export function DownloadDB(arg1) {
  return window['go']['main']['App']['DownloadDB'](arg1);
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function SearchFTS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchFTS'](arg1, arg2, arg3, arg4);
}

export function SearchVector(arg1, arg2) {
  return window['go']['main']['App']['SearchVector'](arg1, arg2);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}
