// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {db} from '../models';

export function AskAssistant(arg1:string):Promise<app.AssistantResponse>;

export function BrowseByCategory(arg1:string,arg2:any,arg3:any):Promise<db.BrowseResult>;

export function BrowseWords(arg1:any,arg2:any,arg3:any,arg4:any):Promise<db.BrowseResult>;

export function GetAPIKey():Promise<any>;

export function GetAppVersion():Promise<string>;

export function GetAttestationsBySource(arg1:string,arg2:any,arg3:any):Promise<db.BrowseResult>;

export function GetCategoryTree():Promise<Array<db.CategoryGroup>>;

export function GetConcordance(arg1:string,arg2:any,arg3:any):Promise<db.BrowseResult>;

export function GetDBInfo():Promise<db.DBInfo>;

export function GetEntry(arg1:number):Promise<db.FullEntryDetail>;

export function GetLanguages():Promise<Array<db.LanguageMeta>>;

export function GetSourcesList():Promise<Array<db.SourceMeta>>;

export function NotifyOpenAbout():Promise<void>;

export function NotifyOpenConfig():Promise<void>;

export function Quit():Promise<void>;

export function SearchFTS(arg1:string,arg2:any,arg3:any,arg4:any):Promise<Array<db.SearchResult>>;

export function SearchVector(arg1:Array<number>,arg2:any):Promise<Array<db.SearchResult>>;

export function SearchVectorQuery(arg1:string,arg2:any):Promise<Array<db.SearchResult>>;

export function SetAPIKey(arg1:string):Promise<void>;

export function StartBuildLocalDB(arg1:boolean):Promise<void>;

export function StartDownloadDB(arg1:any):Promise<void>;
