// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAssistant(arg1) {
  return window['go']['app']['App']['AskAssistant'](arg1);
}

export function BrowseByCategory(arg1, arg2, arg3) {
  return window['go']['app']['App']['BrowseByCategory'](arg1, arg2, arg3);
}

export function BrowseWords(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BrowseWords'](arg1, arg2, arg3, arg4);
}

export function GetAPIKey() {
  return window['go']['app']['App']['GetAPIKey']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetAttestationsBySource(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetAttestationsBySource'](arg1, arg2, arg3);
}

export function GetCategoryTree() {
  return window['go']['app']['App']['GetCategoryTree']();
}

export function GetConcordance(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetConcordance'](arg1, arg2, arg3);
}

export function GetDBInfo() {
  return window['go']['app']['App']['GetDBInfo']();
}

export function GetEntry(arg1) {
  return window['go']['app']['App']['GetEntry'](arg1);
}

export function GetGeminiModel() {
  return window['go']['app']['App']['GetGeminiModel']();
}

export function GetLanguages() {
  return window['go']['app']['App']['GetLanguages']();
}

export function GetSourcesList() {
  return window['go']['app']['App']['GetSourcesList']();
}

export function NotifyOpenAbout() {
  return window['go']['app']['App']['NotifyOpenAbout']();
}

export function NotifyOpenConfig() {
  return window['go']['app']['App']['NotifyOpenConfig']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function SearchFTS(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SearchFTS'](arg1, arg2, arg3, arg4);
}

export function SearchVector(arg1, arg2) {
  return window['go']['app']['App']['SearchVector'](arg1, arg2);
}

export function SearchVectorQuery(arg1, arg2) {
  return window['go']['app']['App']['SearchVectorQuery'](arg1, arg2);
}

export function SetAPIKey(arg1) {
  return window['go']['app']['App']['SetAPIKey'](arg1);
}

export function SetGeminiModel(arg1) {
  return window['go']['app']['App']['SetGeminiModel'](arg1);
}

export function StartBuildLocalDB(arg1) {
  return window['go']['app']['App']['StartBuildLocalDB'](arg1);
}

export function StartDownloadDB(arg1) {
  return window['go']['app']['App']['StartDownloadDB'](arg1);
}
